version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-heroes
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis-geo:
    image: redis:alpine
    container_name: redis-geo
    ports:
      - "6379:6379"

  redis-pop:
    image: redis:alpine
    container_name: redis-pop
    ports:
      - "6380:6379"

  backend:
    build: ./backend
    container_name: airport-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/airport_db
      - REDIS_GEO_URL=redis://redis-geo:6379
      - REDIS_POP_URL=redis://redis-pop:6379
    depends_on:
      - mongo
      - redis-geo
      - redis-pop

  frontend:
    build: ./frontend
    container_name: airport-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
